# ╔══════════════════════════════════════╗
# ║  HYPRPAPER — Wallpaper Config         ║
# ╚══════════════════════════════════════╝

preload = ~/.config/wallpapers/arch-vesper.png
wallpaper = , ~/.config/wallpapers/arch-vesper.png
splash = false
ipc = on
