# ╔══════════════════════════════════════════════════════════════╗
# ║  REFLECTOR — Auto Mirror Optimization                         ║
# ║  Timer runs weekly to keep mirrors fast                        ║
# ╚══════════════════════════════════════════════════════════════╝

--save /etc/pacman.d/mirrorlist
--protocol https
--country Mexico,US,'United States'
--latest 15
--sort rate
--age 12
